/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/message/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MessageController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/message/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MessageController_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EmailController_reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EmailController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserController_create"];
        delete: operations["UserController_delete"];
        options?: never;
        head?: never;
        patch: operations["UserController_update"];
        trace?: never;
    };
    "/api/user/{userId}/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserEmailController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_forgot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        MessageTypeEnumInterface: "EMAIL" | "TELEGRAM";
        MessageResponseEmailAttachmentDto: {
            /** @example invoice.pdf */
            filename?: string | null;
            /** @example application/pdf */
            contentType?: string | null;
            /** @example 102400 */
            size?: number | null;
            /**
             * Format: byte
             * @example JVBERi0xLjQKJcTl8uXrp...
             */
            content: string;
        };
        MessageResponseEmailDataDto: {
            /** @example 123 */
            uid: number;
            /** @example alice@example.com */
            from: string;
            /** @example [
             *       "bob@example.com",
             *       "carol@example.com"
             *     ] */
            to: string[];
            /** @example Meeting reminder */
            subject: string;
            /**
             * Format: date-time
             * @example 2023-01-01T12:00:00.000Z
             */
            date: string;
            /** @example [
             *       "\\Seen",
             *       "\\Flagged"
             *     ] */
            flags: string[];
            /** @example {
             *       "message-id": [
             *         "<id@example.com>"
             *       ],
             *       "x-priority": "high"
             *     } */
            headers: Record<string, never>;
            /** @example Plain text body */
            text?: string | null;
            /** @example <p>HTML body</p> */
            html?: string | null;
            /** @example [] */
            attachments: components["schemas"]["MessageResponseEmailAttachmentDto"][];
            /** @example INBOX */
            mailbox: string;
        };
        MessageResponseEmailDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            uid: number;
            /** @example {} */
            data: components["schemas"]["MessageResponseEmailDataDto"];
        };
        MessageResponseDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            userId: number;
            /** @example EMAIL */
            type: components["schemas"]["MessageTypeEnumInterface"];
            /**
             * Format: date-time
             * @example 2023-01-01T12:00:00.000Z
             */
            readAt: string | null;
            /**
             * Format: date-time
             * @example 2023-01-01T12:00:00.000Z
             */
            dateLastMessage: string;
            /** @example false */
            starred: boolean;
            /** @example John Doe */
            from: string;
            /** @example {} */
            email: components["schemas"]["MessageResponseEmailDto"];
            /**
             * Format: date-time
             * @example 2023-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2023-01-01T00:00:00.000Z
             */
            updatedAt: string;
            /**
             * Format: date-time
             * @example null
             */
            deletedAt?: string | null;
        };
        ListMessageResponseDto: {
            items: components["schemas"]["MessageResponseDto"][];
            /** @example 10 */
            total: number;
        };
        ReplyEmailDto: {
            /** @example Re: Assunto do Email */
            title: string;
            /** @example Olá, este é o corpo do email. */
            body: string;
        };
        SendEmailDto: {
            /** @example Assunto do Email */
            title: string;
            /** @example Olá, este é o corpo do email. */
            body: string;
            /** @example user@email.com */
            to: string;
            /** @example 1 */
            userEmailId: number;
        };
        CreateUserDto: {
            /** @example John Doe */
            name: string;
            /** @example user@email.com */
            email: string;
            /** @example (99) 99999-9999 */
            phone: string;
            /** @example password123 */
            password: string;
            /** @example password123 */
            confirmPassword: string;
        };
        UpdateUserDto: {
            /** @example John Doe */
            name?: string;
            /** @example user@email.com */
            email?: string;
            /** @example (99) 99999-9999 */
            phone?: string;
            /** @example password123 */
            password?: string;
            /** @example password123 */
            confirmPassword?: string;
        };
        LoginRequestDto: {
            /** @example user@email.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        ForgotPasswordDto: {
            /** @example user@email.com */
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MessageController_list: {
        parameters: {
            query: {
                page: number;
                search: string;
                pageSize?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMessageResponseDto"];
                };
            };
        };
    };
    MessageController_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmailController_reply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyEmailDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmailController_send: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserEmailController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                };
            };
        };
    };
    AuthController_forgot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
