# ---------- BUILD ----------
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


FROM node:20-alpine

WORKDIR /usr/src/app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /usr/src/app/dist ./dist
COPY wait-for-redis.sh ./

RUN apk add --no-cache netcat-openbsd && \
    chmod +x wait-for-redis.sh

EXPOSE 8080
CMD ["./wait-for-redis.sh", "${REDIS_HOST:-redis}", "${REDIS_PORT:-6379}", "node", "dist/main.js"]
